let rpgiabIconPack = new Map([
    ["pack_name", "RPGIAB Icon Pack"],
    ["pack_icon", "textures/azalea_icons/other/rpgiab_logo"],
    ["pack_namespace", "rpgiab"],
    ["pack_data", new Map([
  [
    "2d",
    "textures/leaf_icons/2d"
  ],
  [
    "accept",
    "textures/leaf_icons/accept"
  ],
  [
    "add",
    "textures/leaf_icons/add"
  ],
  [
    "ambient_occlusion",
    "textures/leaf_icons/ambient_occlusion"
  ],
  [
    "ambient_occlusion_voxel",
    "textures/leaf_icons/ambient_occlusion_voxel"
  ],
  [
    "ammo",
    "textures/leaf_icons/ammo"
  ],
  [
    "angle",
    "textures/leaf_icons/angle"
  ],
  [
    "anim_frame",
    "textures/leaf_icons/anim_frame"
  ],
  [
    "anim_frame_add",
    "textures/leaf_icons/anim_frame_add"
  ],
  [
    "anim_frame_character",
    "textures/leaf_icons/anim_frame_character"
  ],
  [
    "anim_frame_delete",
    "textures/leaf_icons/anim_frame_delete"
  ],
  [
    "anim_frame_duplicate",
    "textures/leaf_icons/anim_frame_duplicate"
  ],
  [
    "anim_frame_edit",
    "textures/leaf_icons/anim_frame_edit"
  ],
  [
    "anim_frame_move_left",
    "textures/leaf_icons/anim_frame_move_left"
  ],
  [
    "anim_frame_move_right",
    "textures/leaf_icons/anim_frame_move_right"
  ],
  [
    "anim_frame_speed",
    "textures/leaf_icons/anim_frame_speed"
  ],
  [
    "anvil_in",
    "textures/leaf_icons/anvil_in"
  ],
  [
    "anvil_out",
    "textures/leaf_icons/anvil_out"
  ],
  [
    "arguments",
    "textures/leaf_icons/arguments"
  ],
  [
    "arrow_blue_first",
    "textures/leaf_icons/arrow_blue_first"
  ],
  [
    "arrow_blue_last",
    "textures/leaf_icons/arrow_blue_last"
  ],
  [
    "arrow_blue_left",
    "textures/leaf_icons/arrow_blue_left"
  ],
  [
    "arrow_blue_right",
    "textures/leaf_icons/arrow_blue_right"
  ],
  [
    "arrow_branch",
    "textures/leaf_icons/arrow_branch"
  ],
  [
    "arrow_down",
    "textures/leaf_icons/arrow_down"
  ],
  [
    "arrow_in",
    "textures/leaf_icons/arrow_in"
  ],
  [
    "arrow_in_out",
    "textures/leaf_icons/arrow_in_out"
  ],
  [
    "arrow_left",
    "textures/leaf_icons/arrow_left"
  ],
  [
    "arrow_left_right",
    "textures/leaf_icons/arrow_left_right"
  ],
  [
    "arrow_lower",
    "textures/leaf_icons/arrow_lower"
  ],
  [
    "arrow_lower_step",
    "textures/leaf_icons/arrow_lower_step"
  ],
  [
    "arrow_out",
    "textures/leaf_icons/arrow_out"
  ],
  [
    "arrow_play",
    "textures/leaf_icons/arrow_play"
  ],
  [
    "arrow_prompt",
    "textures/leaf_icons/arrow_prompt"
  ],
  [
    "arrow_raise",
    "textures/leaf_icons/arrow_raise"
  ],
  [
    "arrow_raise_step",
    "textures/leaf_icons/arrow_raise_step"
  ],
  [
    "arrow_refresh",
    "textures/leaf_icons/arrow_refresh"
  ],
  [
    "arrow_right",
    "textures/leaf_icons/arrow_right"
  ],
  [
    "arrow_rotate_anticlockwise",
    "textures/leaf_icons/arrow_rotate_anticlockwise"
  ],
  [
    "arrow_rotate_clockwise",
    "textures/leaf_icons/arrow_rotate_clockwise"
  ],
  [
    "arrow_speed",
    "textures/leaf_icons/arrow_speed"
  ],
  [
    "arrow_switch",
    "textures/leaf_icons/arrow_switch"
  ],
  [
    "arrow_up",
    "textures/leaf_icons/arrow_up"
  ],
  [
    "arrow_up_down",
    "textures/leaf_icons/arrow_up_down"
  ],
  [
    "attach",
    "textures/leaf_icons/attach"
  ],
  [
    "autotile",
    "textures/leaf_icons/autotile"
  ],
  [
    "blip_orange",
    "textures/leaf_icons/blip_orange"
  ],
  [
    "bomb",
    "textures/leaf_icons/bomb"
  ],
  [
    "book",
    "textures/leaf_icons/book"
  ],
  [
    "boolean",
    "textures/leaf_icons/boolean"
  ],
  [
    "button",
    "textures/leaf_icons/button"
  ],
  [
    "button_xbox_a",
    "textures/leaf_icons/button_xbox_a"
  ],
  [
    "button_xbox_b",
    "textures/leaf_icons/button_xbox_b"
  ],
  [
    "button_xbox_x",
    "textures/leaf_icons/button_xbox_x"
  ],
  [
    "button_xbox_y",
    "textures/leaf_icons/button_xbox_y"
  ],
  [
    "camera",
    "textures/leaf_icons/camera"
  ],
  [
    "camera_add",
    "textures/leaf_icons/camera_add"
  ],
  [
    "camera_edit",
    "textures/leaf_icons/camera_edit"
  ],
  [
    "camera_first_person",
    "textures/leaf_icons/camera_first_person"
  ],
  [
    "camera_free",
    "textures/leaf_icons/camera_free"
  ],
  [
    "camera_isometric",
    "textures/leaf_icons/camera_isometric"
  ],
  [
    "camera_lock",
    "textures/leaf_icons/camera_lock"
  ],
  [
    "camera_move",
    "textures/leaf_icons/camera_move"
  ],
  [
    "camera_reset",
    "textures/leaf_icons/camera_reset"
  ],
  [
    "camera_rotate",
    "textures/leaf_icons/camera_rotate"
  ],
  [
    "character",
    "textures/leaf_icons/character"
  ],
  [
    "character_add",
    "textures/leaf_icons/character_add"
  ],
  [
    "character_dialogue",
    "textures/leaf_icons/character_dialogue"
  ],
  [
    "character_edit",
    "textures/leaf_icons/character_edit"
  ],
  [
    "character_heart",
    "textures/leaf_icons/character_heart"
  ],
  [
    "character_item_get",
    "textures/leaf_icons/character_item_get"
  ],
  [
    "character_lock",
    "textures/leaf_icons/character_lock"
  ],
  [
    "character_move",
    "textures/leaf_icons/character_move"
  ],
  [
    "character_npc",
    "textures/leaf_icons/character_npc"
  ],
  [
    "character_question",
    "textures/leaf_icons/character_question"
  ],
  [
    "character_rotate",
    "textures/leaf_icons/character_rotate"
  ],
  [
    "character_stop",
    "textures/leaf_icons/character_stop"
  ],
  [
    "checkbox",
    "textures/leaf_icons/checkbox"
  ],
  [
    "checkbox_off",
    "textures/leaf_icons/checkbox_off"
  ],
  [
    "checkmark",
    "textures/leaf_icons/checkmark"
  ],
  [
    "chest",
    "textures/leaf_icons/chest"
  ],
  [
    "chest_checkmark",
    "textures/leaf_icons/chest_checkmark"
  ],
  [
    "chest_delete",
    "textures/leaf_icons/chest_delete"
  ],
  [
    "chest_disable",
    "textures/leaf_icons/chest_disable"
  ],
  [
    "chest_enable",
    "textures/leaf_icons/chest_enable"
  ],
  [
    "chest_item",
    "textures/leaf_icons/chest_item"
  ],
  [
    "clear",
    "textures/leaf_icons/clear"
  ],
  [
    "clipboard",
    "textures/leaf_icons/clipboard"
  ],
  [
    "clock",
    "textures/leaf_icons/clock"
  ],
  [
    "clock_play",
    "textures/leaf_icons/clock_play"
  ],
  [
    "clock_stop",
    "textures/leaf_icons/clock_stop"
  ],
  [
    "coins",
    "textures/leaf_icons/coins"
  ],
  [
    "collapse",
    "textures/leaf_icons/collapse"
  ],
  [
    "color_edit",
    "textures/leaf_icons/color_edit"
  ],
  [
    "color_swatch",
    "textures/leaf_icons/color_swatch"
  ],
  [
    "comment",
    "textures/leaf_icons/comment"
  ],
  [
    "computer",
    "textures/leaf_icons/computer"
  ],
  [
    "console",
    "textures/leaf_icons/console"
  ],
  [
    "credits",
    "textures/leaf_icons/credits"
  ],
  [
    "crosshair",
    "textures/leaf_icons/crosshair"
  ],
  [
    "cursor",
    "textures/leaf_icons/cursor"
  ],
  [
    "delete",
    "textures/leaf_icons/delete"
  ],
  [
    "dialogue",
    "textures/leaf_icons/dialogue"
  ],
  [
    "dialogue_add",
    "textures/leaf_icons/dialogue_add"
  ],
  [
    "dialogue_page",
    "textures/leaf_icons/dialogue_page"
  ],
  [
    "dialogue_start",
    "textures/leaf_icons/dialogue_start"
  ],
  [
    "dice",
    "textures/leaf_icons/dice"
  ],
  [
    "discord_logo",
    "textures/leaf_icons/discord_logo"
  ],
  [
    "disk",
    "textures/leaf_icons/disk"
  ],
  [
    "disk_load",
    "textures/leaf_icons/disk_load"
  ],
  [
    "disk_multiple",
    "textures/leaf_icons/disk_multiple"
  ],
  [
    "disk_save",
    "textures/leaf_icons/disk_save"
  ],
  [
    "door",
    "textures/leaf_icons/door"
  ],
  [
    "enemy",
    "textures/leaf_icons/enemy"
  ],
  [
    "enemy_add",
    "textures/leaf_icons/enemy_add"
  ],
  [
    "entity",
    "textures/leaf_icons/entity"
  ],
  [
    "entity_bounds",
    "textures/leaf_icons/entity_bounds"
  ],
  [
    "entity_delete",
    "textures/leaf_icons/entity_delete"
  ],
  [
    "entity_move",
    "textures/leaf_icons/entity_move"
  ],
  [
    "exclamation",
    "textures/leaf_icons/exclamation"
  ],
  [
    "exit",
    "textures/leaf_icons/exit"
  ],
  [
    "expand",
    "textures/leaf_icons/expand"
  ],
  [
    "expression",
    "textures/leaf_icons/expression"
  ],
  [
    "eye",
    "textures/leaf_icons/eye"
  ],
  [
    "eyedropper",
    "textures/leaf_icons/eyedropper"
  ],
  [
    "eye_height",
    "textures/leaf_icons/eye_height"
  ],
  [
    "eye_hide",
    "textures/leaf_icons/eye_hide"
  ],
  [
    "eye_lock",
    "textures/leaf_icons/eye_lock"
  ],
  [
    "eye_show",
    "textures/leaf_icons/eye_show"
  ],
  [
    "fade_in",
    "textures/leaf_icons/fade_in"
  ],
  [
    "fade_out",
    "textures/leaf_icons/fade_out"
  ],
  [
    "flag_blue",
    "textures/leaf_icons/flag_blue"
  ],
  [
    "flip_horizontal",
    "textures/leaf_icons/flip_horizontal"
  ],
  [
    "folder",
    "textures/leaf_icons/folder"
  ],
  [
    "folder_image",
    "textures/leaf_icons/folder_image"
  ],
  [
    "folder_page",
    "textures/leaf_icons/folder_page"
  ],
  [
    "folder_search",
    "textures/leaf_icons/folder_search"
  ],
  [
    "folder_settings",
    "textures/leaf_icons/folder_settings"
  ],
  [
    "folder_up",
    "textures/leaf_icons/folder_up"
  ],
  [
    "folder_voxel",
    "textures/leaf_icons/folder_voxel"
  ],
  [
    "font",
    "textures/leaf_icons/font"
  ],
  [
    "font_size",
    "textures/leaf_icons/font_size"
  ],
  [
    "fullscreen",
    "textures/leaf_icons/fullscreen"
  ],
  [
    "function",
    "textures/leaf_icons/function"
  ],
  [
    "gear",
    "textures/leaf_icons/gear"
  ],
  [
    "glow",
    "textures/leaf_icons/glow"
  ],
  [
    "godot_logo",
    "textures/leaf_icons/godot_logo"
  ],
  [
    "gradient_red",
    "textures/leaf_icons/gradient_red"
  ],
  [
    "grid",
    "textures/leaf_icons/grid"
  ],
  [
    "grid_height",
    "textures/leaf_icons/grid_height"
  ],
  [
    "grid_tile",
    "textures/leaf_icons/grid_tile"
  ],
  [
    "grid_tile_place",
    "textures/leaf_icons/grid_tile_place"
  ],
  [
    "ground",
    "textures/leaf_icons/ground"
  ],
  [
    "group",
    "textures/leaf_icons/group"
  ],
  [
    "group_add",
    "textures/leaf_icons/group_add"
  ],
  [
    "group_delete",
    "textures/leaf_icons/group_delete"
  ],
  [
    "group_edit",
    "textures/leaf_icons/group_edit"
  ],
  [
    "group_mesh",
    "textures/leaf_icons/group_mesh"
  ],
  [
    "group_tiles",
    "textures/leaf_icons/group_tiles"
  ],
  [
    "hand",
    "textures/leaf_icons/hand"
  ],
  [
    "hand_add",
    "textures/leaf_icons/hand_add"
  ],
  [
    "hand_delete",
    "textures/leaf_icons/hand_delete"
  ],
  [
    "hand_move",
    "textures/leaf_icons/hand_move"
  ],
  [
    "heart",
    "textures/leaf_icons/heart"
  ],
  [
    "heart_add",
    "textures/leaf_icons/heart_add"
  ],
  [
    "heart_delete",
    "textures/leaf_icons/heart_delete"
  ],
  [
    "help",
    "textures/leaf_icons/help"
  ],
  [
    "hourglass",
    "textures/leaf_icons/hourglass"
  ],
  [
    "image",
    "textures/leaf_icons/image"
  ],
  [
    "image_add",
    "textures/leaf_icons/image_add"
  ],
  [
    "image_dimensions",
    "textures/leaf_icons/image_dimensions"
  ],
  [
    "image_hand",
    "textures/leaf_icons/image_hand"
  ],
  [
    "import_export",
    "textures/leaf_icons/import_export"
  ],
  [
    "information",
    "textures/leaf_icons/information"
  ],
  [
    "interact",
    "textures/leaf_icons/interact"
  ],
  [
    "inventory",
    "textures/leaf_icons/inventory"
  ],
  [
    "inventory_hide",
    "textures/leaf_icons/inventory_hide"
  ],
  [
    "inventory_show",
    "textures/leaf_icons/inventory_show"
  ],
  [
    "itch_logo",
    "textures/leaf_icons/itch_logo"
  ],
  [
    "item",
    "textures/leaf_icons/item"
  ],
  [
    "item_add",
    "textures/leaf_icons/item_add"
  ],
  [
    "item_delete",
    "textures/leaf_icons/item_delete"
  ],
  [
    "item_drop",
    "textures/leaf_icons/item_drop"
  ],
  [
    "item_stack",
    "textures/leaf_icons/item_stack"
  ],
  [
    "joystick",
    "textures/leaf_icons/joystick"
  ],
  [
    "jump",
    "textures/leaf_icons/jump"
  ],
  [
    "keyboard",
    "textures/leaf_icons/keyboard"
  ],
  [
    "key_c",
    "textures/leaf_icons/key_c"
  ],
  [
    "key_t",
    "textures/leaf_icons/key_t"
  ],
  [
    "ladder",
    "textures/leaf_icons/ladder"
  ],
  [
    "ladder_character",
    "textures/leaf_icons/ladder_character"
  ],
  [
    "ladder_down",
    "textures/leaf_icons/ladder_down"
  ],
  [
    "ladder_lock",
    "textures/leaf_icons/ladder_lock"
  ],
  [
    "ladder_none",
    "textures/leaf_icons/ladder_none"
  ],
  [
    "ladder_up",
    "textures/leaf_icons/ladder_up"
  ],
  [
    "ladder_up_down",
    "textures/leaf_icons/ladder_up_down"
  ],
  [
    "laser",
    "textures/leaf_icons/laser"
  ],
  [
    "library",
    "textures/leaf_icons/library"
  ],
  [
    "light",
    "textures/leaf_icons/light"
  ],
  [
    "light_add",
    "textures/leaf_icons/light_add"
  ],
  [
    "light_energy",
    "textures/leaf_icons/light_energy"
  ],
  [
    "light_fade",
    "textures/leaf_icons/light_fade"
  ],
  [
    "light_negative",
    "textures/leaf_icons/light_negative"
  ],
  [
    "light_off",
    "textures/leaf_icons/light_off"
  ],
  [
    "light_on_off",
    "textures/leaf_icons/light_on_off"
  ],
  [
    "light_range",
    "textures/leaf_icons/light_range"
  ],
  [
    "link",
    "textures/leaf_icons/link"
  ],
  [
    "link_add",
    "textures/leaf_icons/link_add"
  ],
  [
    "link_box",
    "textures/leaf_icons/link_box"
  ],
  [
    "link_delete",
    "textures/leaf_icons/link_delete"
  ],
  [
    "link_eye",
    "textures/leaf_icons/link_eye"
  ],
  [
    "linux_logo",
    "textures/leaf_icons/linux_logo"
  ],
  [
    "loading_screen",
    "textures/leaf_icons/loading_screen"
  ],
  [
    "location",
    "textures/leaf_icons/location"
  ],
  [
    "location_character",
    "textures/leaf_icons/location_character"
  ],
  [
    "location_enemy",
    "textures/leaf_icons/location_enemy"
  ],
  [
    "location_hand",
    "textures/leaf_icons/location_hand"
  ],
  [
    "lock",
    "textures/leaf_icons/lock"
  ],
  [
    "lock_vertical",
    "textures/leaf_icons/lock_vertical"
  ],
  [
    "mac_logo",
    "textures/leaf_icons/mac_logo"
  ],
  [
    "magnifier",
    "textures/leaf_icons/magnifier"
  ],
  [
    "magnifier_zoom_in",
    "textures/leaf_icons/magnifier_zoom_in"
  ],
  [
    "magnifier_zoom_out",
    "textures/leaf_icons/magnifier_zoom_out"
  ],
  [
    "main_menu",
    "textures/leaf_icons/main_menu"
  ],
  [
    "map",
    "textures/leaf_icons/map"
  ],
  [
    "map_add",
    "textures/leaf_icons/map_add"
  ],
  [
    "map_fog",
    "textures/leaf_icons/map_fog"
  ],
  [
    "map_link",
    "textures/leaf_icons/map_link"
  ],
  [
    "map_reset",
    "textures/leaf_icons/map_reset"
  ],
  [
    "map_start",
    "textures/leaf_icons/map_start"
  ],
  [
    "margin_bottom",
    "textures/leaf_icons/margin_bottom"
  ],
  [
    "margin_left",
    "textures/leaf_icons/margin_left"
  ],
  [
    "margin_right",
    "textures/leaf_icons/margin_right"
  ],
  [
    "margin_top",
    "textures/leaf_icons/margin_top"
  ],
  [
    "margin_top_left",
    "textures/leaf_icons/margin_top_left"
  ],
  [
    "mesh_default",
    "textures/leaf_icons/mesh_default"
  ],
  [
    "mesh_marching",
    "textures/leaf_icons/mesh_marching"
  ],
  [
    "mesh_preview",
    "textures/leaf_icons/mesh_preview"
  ],
  [
    "message",
    "textures/leaf_icons/message"
  ],
  [
    "missing",
    "textures/leaf_icons/missing"
  ],
  [
    "model_edit",
    "textures/leaf_icons/model_edit"
  ],
  [
    "mouse",
    "textures/leaf_icons/mouse"
  ],
  [
    "mouse_eye",
    "textures/leaf_icons/mouse_eye"
  ],
  [
    "mouse_free",
    "textures/leaf_icons/mouse_free"
  ],
  [
    "move_interact",
    "textures/leaf_icons/move_interact"
  ],
  [
    "music",
    "textures/leaf_icons/music"
  ],
  [
    "music_play",
    "textures/leaf_icons/music_play"
  ],
  [
    "navigation",
    "textures/leaf_icons/navigation"
  ],
  [
    "navigation_adjacent",
    "textures/leaf_icons/navigation_adjacent"
  ],
  [
    "node",
    "textures/leaf_icons/node"
  ],
  [
    "node_add",
    "textures/leaf_icons/node_add"
  ],
  [
    "node_copy",
    "textures/leaf_icons/node_copy"
  ],
  [
    "node_library",
    "textures/leaf_icons/node_library"
  ],
  [
    "node_link",
    "textures/leaf_icons/node_link"
  ],
  [
    "noise",
    "textures/leaf_icons/noise"
  ],
  [
    "number",
    "textures/leaf_icons/number"
  ],
  [
    "object",
    "textures/leaf_icons/object"
  ],
  [
    "object_add",
    "textures/leaf_icons/object_add"
  ],
  [
    "object_hand",
    "textures/leaf_icons/object_hand"
  ],
  [
    "offset_horizontal",
    "textures/leaf_icons/offset_horizontal"
  ],
  [
    "offset_vertical",
    "textures/leaf_icons/offset_vertical"
  ],
  [
    "package",
    "textures/leaf_icons/package"
  ],
  [
    "page_add",
    "textures/leaf_icons/page_add"
  ],
  [
    "page_copy",
    "textures/leaf_icons/page_copy"
  ],
  [
    "page_data",
    "textures/leaf_icons/page_data"
  ],
  [
    "page_edit",
    "textures/leaf_icons/page_edit"
  ],
  [
    "page_voxel",
    "textures/leaf_icons/page_voxel"
  ],
  [
    "paint_can",
    "textures/leaf_icons/paint_can"
  ],
  [
    "palette",
    "textures/leaf_icons/palette"
  ],
  [
    "party",
    "textures/leaf_icons/party"
  ],
  [
    "party_add",
    "textures/leaf_icons/party_add"
  ],
  [
    "party_delete",
    "textures/leaf_icons/party_delete"
  ],
  [
    "party_reset",
    "textures/leaf_icons/party_reset"
  ],
  [
    "pause",
    "textures/leaf_icons/pause"
  ],
  [
    "pencil",
    "textures/leaf_icons/pencil"
  ],
  [
    "platform",
    "textures/leaf_icons/platform"
  ],
  [
    "play",
    "textures/leaf_icons/play"
  ],
  [
    "portrait",
    "textures/leaf_icons/portrait"
  ],
  [
    "portrait_left",
    "textures/leaf_icons/portrait_left"
  ],
  [
    "portrait_right",
    "textures/leaf_icons/portrait_right"
  ],
  [
    "potion",
    "textures/leaf_icons/potion"
  ],
  [
    "progress_bar",
    "textures/leaf_icons/progress_bar"
  ],
  [
    "properties",
    "textures/leaf_icons/properties"
  ],
  [
    "properties_edit",
    "textures/leaf_icons/properties_edit"
  ],
  [
    "properties_insert",
    "textures/leaf_icons/properties_insert"
  ],
  [
    "puzzle",
    "textures/leaf_icons/puzzle"
  ],
  [
    "redo",
    "textures/leaf_icons/redo"
  ],
  [
    "rpgiab_logo",
    "textures/leaf_icons/rpgiab_logo"
  ],
  [
    "scissors",
    "textures/leaf_icons/scissors"
  ],
  [
    "script",
    "textures/leaf_icons/script"
  ],
  [
    "script_add",
    "textures/leaf_icons/script_add"
  ],
  [
    "script_code",
    "textures/leaf_icons/script_code"
  ],
  [
    "script_delete",
    "textures/leaf_icons/script_delete"
  ],
  [
    "script_edit",
    "textures/leaf_icons/script_edit"
  ],
  [
    "script_lightning",
    "textures/leaf_icons/script_lightning"
  ],
  [
    "script_lightning_add",
    "textures/leaf_icons/script_lightning_add"
  ],
  [
    "script_lightning_edit",
    "textures/leaf_icons/script_lightning_edit"
  ],
  [
    "script_start",
    "textures/leaf_icons/script_start"
  ],
  [
    "script_text",
    "textures/leaf_icons/script_text"
  ],
  [
    "script_text_add",
    "textures/leaf_icons/script_text_add"
  ],
  [
    "script_text_checkmark",
    "textures/leaf_icons/script_text_checkmark"
  ],
  [
    "script_text_delete",
    "textures/leaf_icons/script_text_delete"
  ],
  [
    "select_edit",
    "textures/leaf_icons/select_edit"
  ],
  [
    "settings_gear",
    "textures/leaf_icons/settings_gear"
  ],
  [
    "settings_save",
    "textures/leaf_icons/settings_save"
  ],
  [
    "shadow",
    "textures/leaf_icons/shadow"
  ],
  [
    "shadow_darkness",
    "textures/leaf_icons/shadow_darkness"
  ],
  [
    "shield",
    "textures/leaf_icons/shield"
  ],
  [
    "ship",
    "textures/leaf_icons/ship"
  ],
  [
    "skull",
    "textures/leaf_icons/skull"
  ],
  [
    "skull_delete",
    "textures/leaf_icons/skull_delete"
  ],
  [
    "sound",
    "textures/leaf_icons/sound"
  ],
  [
    "star",
    "textures/leaf_icons/star"
  ],
  [
    "steam_logo",
    "textures/leaf_icons/steam_logo"
  ],
  [
    "stop",
    "textures/leaf_icons/stop"
  ],
  [
    "stop_sign",
    "textures/leaf_icons/stop_sign"
  ],
  [
    "string",
    "textures/leaf_icons/string"
  ],
  [
    "surface_edges",
    "textures/leaf_icons/surface_edges"
  ],
  [
    "sword",
    "textures/leaf_icons/sword"
  ],
  [
    "swords",
    "textures/leaf_icons/swords"
  ],
  [
    "sword_blood",
    "textures/leaf_icons/sword_blood"
  ],
  [
    "sword_eye",
    "textures/leaf_icons/sword_eye"
  ],
  [
    "sword_hit",
    "textures/leaf_icons/sword_hit"
  ],
  [
    "sword_link",
    "textures/leaf_icons/sword_link"
  ],
  [
    "sword_reset",
    "textures/leaf_icons/sword_reset"
  ],
  [
    "sword_start",
    "textures/leaf_icons/sword_start"
  ],
  [
    "sword_stop",
    "textures/leaf_icons/sword_stop"
  ],
  [
    "tab",
    "textures/leaf_icons/tab"
  ],
  [
    "tag_blue",
    "textures/leaf_icons/tag_blue"
  ],
  [
    "tag_id",
    "textures/leaf_icons/tag_id"
  ],
  [
    "terrain",
    "textures/leaf_icons/terrain"
  ],
  [
    "terrain_follow",
    "textures/leaf_icons/terrain_follow"
  ],
  [
    "terrain_precise",
    "textures/leaf_icons/terrain_precise"
  ],
  [
    "terrain_smooth_curve",
    "textures/leaf_icons/terrain_smooth_curve"
  ],
  [
    "terrain_smooth_linear",
    "textures/leaf_icons/terrain_smooth_linear"
  ],
  [
    "text",
    "textures/leaf_icons/text"
  ],
  [
    "text_align_center",
    "textures/leaf_icons/text_align_center"
  ],
  [
    "text_bullets",
    "textures/leaf_icons/text_bullets"
  ],
  [
    "text_eye",
    "textures/leaf_icons/text_eye"
  ],
  [
    "text_field",
    "textures/leaf_icons/text_field"
  ],
  [
    "text_line_numbers",
    "textures/leaf_icons/text_line_numbers"
  ],
  [
    "text_line_spacing",
    "textures/leaf_icons/text_line_spacing"
  ],
  [
    "tile",
    "textures/leaf_icons/tile"
  ],
  [
    "tile_add",
    "textures/leaf_icons/tile_add"
  ],
  [
    "tile_enter",
    "textures/leaf_icons/tile_enter"
  ],
  [
    "tile_exclamation",
    "textures/leaf_icons/tile_exclamation"
  ],
  [
    "tile_exit",
    "textures/leaf_icons/tile_exit"
  ],
  [
    "tile_impassable",
    "textures/leaf_icons/tile_impassable"
  ],
  [
    "tile_passable",
    "textures/leaf_icons/tile_passable"
  ],
  [
    "tile_stop",
    "textures/leaf_icons/tile_stop"
  ],
  [
    "tools",
    "textures/leaf_icons/tools"
  ],
  [
    "tool_items",
    "textures/leaf_icons/tool_items"
  ],
  [
    "transparency",
    "textures/leaf_icons/transparency"
  ],
  [
    "tree_collapse",
    "textures/leaf_icons/tree_collapse"
  ],
  [
    "tree_expand",
    "textures/leaf_icons/tree_expand"
  ],
  [
    "trello_logo",
    "textures/leaf_icons/trello_logo"
  ],
  [
    "twitter_logo",
    "textures/leaf_icons/twitter_logo"
  ],
  [
    "ui",
    "textures/leaf_icons/ui"
  ],
  [
    "ui_inventory",
    "textures/leaf_icons/ui_inventory"
  ],
  [
    "ui_toolbar",
    "textures/leaf_icons/ui_toolbar"
  ],
  [
    "undo",
    "textures/leaf_icons/undo"
  ],
  [
    "unlock",
    "textures/leaf_icons/unlock"
  ],
  [
    "variable",
    "textures/leaf_icons/variable"
  ],
  [
    "variable_return",
    "textures/leaf_icons/variable_return"
  ],
  [
    "voxel",
    "textures/leaf_icons/voxel"
  ],
  [
    "voxel_add",
    "textures/leaf_icons/voxel_add"
  ],
  [
    "voxel_editor",
    "textures/leaf_icons/voxel_editor"
  ],
  [
    "voxel_outlines",
    "textures/leaf_icons/voxel_outlines"
  ],
  [
    "voxel_paint",
    "textures/leaf_icons/voxel_paint"
  ],
  [
    "warning",
    "textures/leaf_icons/warning"
  ],
  [
    "weapons",
    "textures/leaf_icons/weapons"
  ],
  [
    "weather_fog",
    "textures/leaf_icons/weather_fog"
  ],
  [
    "weather_sun",
    "textures/leaf_icons/weather_sun"
  ],
  [
    "widget",
    "textures/leaf_icons/widget"
  ],
  [
    "widget_height",
    "textures/leaf_icons/widget_height"
  ],
  [
    "widget_hide",
    "textures/leaf_icons/widget_hide"
  ],
  [
    "widget_lock",
    "textures/leaf_icons/widget_lock"
  ],
  [
    "widget_save",
    "textures/leaf_icons/widget_save"
  ],
  [
    "widget_show",
    "textures/leaf_icons/widget_show"
  ],
  [
    "widget_width",
    "textures/leaf_icons/widget_width"
  ],
  [
    "windows_logo",
    "textures/leaf_icons/windows_logo"
  ],
  [
    "window_compact_off",
    "textures/leaf_icons/window_compact_off"
  ],
  [
    "window_compact_on",
    "textures/leaf_icons/window_compact_on"
  ],
  [
    "window_dialogue",
    "textures/leaf_icons/window_dialogue"
  ],
  [
    "window_expand_down",
    "textures/leaf_icons/window_expand_down"
  ],
  [
    "window_expand_up",
    "textures/leaf_icons/window_expand_up"
  ],
  [
    "window_frame_show",
    "textures/leaf_icons/window_frame_show"
  ],
  [
    "window_free",
    "textures/leaf_icons/window_free"
  ],
  [
    "window_title_show",
    "textures/leaf_icons/window_title_show"
  ],
  [
    "window_width",
    "textures/leaf_icons/window_width"
  ],
  [
    "wizard",
    "textures/leaf_icons/wizard"
  ],
  [
    "world",
    "textures/leaf_icons/world"
  ],
  [
    "world_disable",
    "textures/leaf_icons/world_disable"
  ],
  [
    "world_disk",
    "textures/leaf_icons/world_disk"
  ],
  [
    "world_enable",
    "textures/leaf_icons/world_enable"
  ],
  [
    "world_hand",
    "textures/leaf_icons/world_hand"
  ],
  [
    "world_page",
    "textures/leaf_icons/world_page"
  ],
  [
    "xp",
    "textures/leaf_icons/xp"
  ],
  [
    "yield",
    "textures/leaf_icons/yield"
  ],
  [
    "yield_add",
    "textures/leaf_icons/yield_add"
  ]
])]
]);
export { rpgiabIconPack }